"""
ArchitectureContext and supporting Pydantic v2 models.

These models represent the structured architectural analysis generated by the
ArchitectureAgent.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Architecture models
# ---------------------------------------------------------------------------


class ComponentDescription(BaseModel):
    """A major component or module within the repository."""

    name: str = Field(..., description="Name of the component or module.")
    description: str = Field(..., description="Brief description of its responsibility.")
    key_files: list[str] = Field(
        default_factory=list, description="Primary files or directories representing this component."
    )


class ArchitectureAnalysis(BaseModel):
    """
    Structured architectural analysis generated by the ArchitectureAgent.
    """

    project_type: str = Field(
        ...,
        description="General classification of the project (e.g., 'Web Application', 'CLI Tool', 'Library').",
    )
    architecture_style: str = Field(
        ...,
        description="Detected architectural pattern (e.g., 'MVC', 'Clean Architecture', 'Monolith', 'Microservice').",
    )
    primary_framework: str | None = Field(
        None, description="The main framework driving the application, if any."
    )
    backend_framework: str | None = Field(
        None, description="Backend framework used (e.g., 'FastAPI', 'Django'), if any."
    )
    frontend_framework: str | None = Field(
        None, description="Frontend framework used (e.g., 'React', 'Vue'), if any."
    )

    major_components: list[ComponentDescription] = Field(
        default_factory=list,
        description="Key structural components of the codebase.",
    )
    dependency_summary: str = Field(
        ..., description="Brief summary of how the project manages dependencies."
    )
    build_process: str = Field(
        ..., description="Summary of the build/compilation process, or 'None' if interpreted."
    )
    testing_strategy: str = Field(
        ..., description="Observed approach to testing (frameworks, coverage patterns)."
    )
    deployment_indicators: str = Field(
        ..., description="Traces of deployment mechanisms (Docker, GitHub Actions, Vercel, etc.)."
    )

    design_patterns: list[str] = Field(
        default_factory=list,
        description="Notable software design patterns detected in the code structure.",
    )
    strengths: list[str] = Field(
        default_factory=list,
        description="Architectural strong points of the repository.",
    )
    potential_improvements: list[str] = Field(
        default_factory=list,
        description="Areas where the architecture could be improved or refactored.",
    )
    scalability_notes: str = Field(
        ..., description="Observations regarding how well the architecture might scale."
    )
    maintainability_notes: str = Field(
        ..., description="Observations regarding code maintainability and technical debt."
    )
