"""
ContributionContext and supporting Pydantic v2 models.

These models represent the structured contribution recommendations generated
by the ContributionAgent.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Contribution models
# ---------------------------------------------------------------------------

DifficultyLevel = Literal["Beginner", "Intermediate", "Advanced"]
ImpactLevel = Literal["Low", "Medium", "High"]
RiskLevel = Literal["Low", "Medium", "High"]


class LearningStep(BaseModel):
    """A single step in a learning path."""
    
    instruction: str = Field(..., description="Actionable learning instruction (e.g., 'Read src/auth.py').")


class LearningPath(BaseModel):
    """A learning path outlining how to acquire the necessary context."""

    steps: list[LearningStep] = Field(
        default_factory=list, description="Ordered list of steps to learn the required concepts."
    )
    estimated_learning_time: str = Field(
        ..., description="Estimated time to complete the learning path (e.g., '30 minutes')."
    )


class ContributionRecommendation(BaseModel):
    """
    A structured contribution opportunity generated by the ContributionAgent.
    """

    title: str = Field(..., description="A clear, concise title for the contribution.")
    description: str = Field(..., description="Detailed explanation of what needs to be done.")
    category: str = Field(
        ...,
        description=(
            "The category of the contribution. Must be one of: Documentation, Testing, Bug Fixes, "
            "Refactoring, Performance, Security, Accessibility, Developer Experience, CI/CD, "
            "Code Quality, Features, Architecture, Dependencies, Examples/Tutorials, or DevOps."
        ),
    )
    tags: list[str] = Field(default_factory=list, description="Relevant tags (e.g., 'python', 'api').")
    
    difficulty: DifficultyLevel = Field(..., description="Beginner, Intermediate, or Advanced.")
    estimated_time: str = Field(..., description="Estimated time to complete the actual contribution.")
    impact: ImpactLevel = Field(..., description="Low, Medium, or High impact on the project.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Agent's confidence in this recommendation (0.0 to 1.0).")
    
    duplicate_risk: RiskLevel = Field(
        ..., description="Risk that this is already being worked on (Low, Medium, High)."
    )
    duplicate_risk_reasoning: str = Field(
        ..., description="Explanation of the duplicate risk based on open issues and PRs."
    )
    
    suggested_files: list[str] = Field(
        default_factory=list, description="Relative paths to files that likely need to be modified."
    )
    
    learning_path: LearningPath = Field(..., description="A step-by-step guide to get up to speed.")
    
    mentor_advice: list[str] = Field(
        default_factory=list, description="Practical tips from an experienced maintainer's perspective."
    )
    
    why_this_matters: str = Field(
        ..., description="Explanation of why this contribution provides value to the project."
    )
    expected_learning_outcome: str = Field(
        ..., description="What the contributor will learn by completing this task."
    )
    reasoning: str = Field(
        ..., description="Overall reasoning for why this contribution was selected and prioritized."
    )


class ContributionCandidateList(BaseModel):
    """
    Internal model used during the two-step generation process to represent
    the final selected list of balanced recommendations.
    """
    
    recommendations: list[ContributionRecommendation] = Field(
        ..., description="The final filtered and ranked list of contributions."
    )
